/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <QDebug>
/* Header for class com_hungkv_autolike_communication_WeakUpLibrary */

#ifndef _Included_com_hungkv_autolike_communication_WeakUpLibrary
#define _Included_com_hungkv_autolike_communication_WeakUpLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hungkv_autolike_communication_WeakUpLibrary
 * Method:    callLibrary
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_hungkv_autolike_communication_WeakUpLibrary_callLibrary
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
